server:
  port: 9210
  
  
# 服务熔断、降级     
feign: 
   hystrix: 
      enable: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
eureka:  client:    #register-with-eureka: false
    service-url:      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #将服务注册进Eureka集群
  instance:
    instance-id: snailshop-consumer-cart-feign-9210   #自定义服务名称信息（别名处理）
    prefer-ip-address: true                     #访问路径可以显示IP地址
spring:
    application:
        name: snailshop-consumer-cart  

info: #信息展示
  app.name: snailshop-consumer-cart-feign-9210
  company.name: www.snailshell.com.cn
  build.artifactId: $project.artifact$
  build.version: $project.version$    
