server:
   port: 9001
   
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml               #mybatis配置文件所在路径
    type-aliases-package: cn.com.snailshell.snailshop.entities       #所有Entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                               #mapper映射文件
    

spring:
    application:
        name: snailshop-provider-pay                            #注册到eureka后的微服务名称
    redis: 
     host: 192.168.191.1
     port: 6379
    jackson:
     default-property-inclusion: NON_NULL         
    datasource:
     type: com.alibaba.druid.pool.DruidDataSource            #当前数据源操作类型
     driver-class-name: com.mysql.jdbc.Driver                #mysql驱动包
     url: jdbc:mysql://localhost:3306/db_snailshop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
     username: root
     password: root
     dbcp2:
      min-idle: 5                             #数据库连接池维持的最小连接数
      initial-size: 5                         #初始化链接数
      max-total: 5                            #最大连接数
      max-wait-millis: 6000                   #等待连接获取的最大超时时间 
      log-abandoned: true
    rabbitmq:
     host: 192.168.30.132 
     
#微信支付相关
wxPayConfig:
     appID: wxab8acb865bb1637e
     mchID: 11473623
     key: 2ab9071b06b9f739b950ddb41db2690d
     notify_url:  http://f3qcmb.natappfree.cc/api/wxPayNotify
     
#支付宝支付相关
alipay:
   appid: YOUR_APPID
   merchant_private_key: YOUR_KEY
   alipay_public_key:YOUR_KEY
   return_url: http://localhost:9001/api/callBack
   notify_url: http://ip/api/payNotify
   sign_type: RSA2
   charset: utf-8
   gatewayUrl: https://openapi.alipaydev.com/gateway.do
   
